### ISSUE TITLE
Doc Generation Config - Improve workflow 

### ISSUE THREAD

**Issue by barnjamin** [wormhole-foundation/docs.wormhole.com#5]
The workflow for generating docs or pulling in content needs to be improved

```[tasklist]
### Tasks
- [ ] New directory and new JSON file per chain for extra details
- [ ] Move logic from shell scripts into TS scripts
- [ ] Add some triggered CI job to ensure docs are up to date
```
